chrome_public_manifest_package = "io.dioide.aerium"
target_os = "android"
target_cpu = "arm64"
build_apk_secondary_abi = false
is_desktop_android = false
is_official_build = true
is_debug = false
is_component_build = false
chrome_pgo_phase = 2
use_thin_lto = false
symbol_level = 0
blink_symbol_level = 0
v8_symbol_level = 0
dcheck_always_on = false
enable_iterator_debugging = false
disable_fieldtrial_testing_config = true
enable_basic_printing = true
enable_print_preview = false
enable_plugins = false
enable_pdf = false
proprietary_codecs = true
ffmpeg_branding = "Chrome"
enable_av1_decoder = true
enable_dav1d_decoder = true
safe_browsing_mode = 0
enable_reporting = false
enable_vr = false
enable_arcore = false
enable_openxr = false
enable_cardboard = false
enable_remoting = false
build_contextual_search = false
google_api_key = ""
google_default_client_id = ""
google_default_client_secret = ""
use_siso = true
use_login_database_as_backend = true
exclude_unwind_tables = false
icu_use_data_file = true
rtc_build_examples = false
use_errorprone_java_compiler = false
use_rtti = false
include_both_v8_snapshots = false
include_both_v8_snapshots_android_secondary_abi = false
generate_linker_map = false
build_with_tflite_lib = false

enable_extensions = true
enable_desktop_android_extensions = true